version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.3
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - app-network
        command: ["nginx-debug", "-g", "daemon off;"]

    pgsql:
        image: postgres:16
        ports:
            - '5432:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - ./storage/app/postgresql:/var/lib/postgresql/data
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s

    redis:
        image: redis:alpine
        ports:
            - '6379:6379'
        volumes:
            - ./storage/app/redis:/data
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s

networks:
    app-network:
        driver: bridge
